### ISSUE TITLE
socket1.py

### ISSUE THREAD

**Issue by sandeepkumarkolli** [jeremylinlin/coursera-using-python-to-access-web-data#1]
for this code 
import socket
mysock=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
mysock.connect(('www.data.pr4e.org', 80))
mysock.send('GET http://www.data.pr4e.org/intro-short.txt HTTP\1.0\n\n'.encode())
while True:
    data=mysock.recv(512)
    if (len(data)<1):
        break
    print data
mysock.close()
 
**how can i get ETag:**

**Comment by jeremy-wl** [comment]
Sorry dude it's been too long since I finished this course. I can't help you with that right now.
